name: Check Tennis Court

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  check:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: browser-actions/setup-edge@v1
        with:
          edge-version: stable
          install-edgedriver: true

      - name: Run tennis checker
        shell: pwsh
        env:
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}
        run: |
          .\src\tennis\bin\katsushika_tennis2.ps1


          
