name: Check Tennis Court

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  check:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run tennis checker
        shell: pwsh
        env:
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}
        run: |
          .\tennis\bin\katsushika_tennis2.ps1
